language: clojure
lein: lein
dist: trusty
jdk:
   - oraclejdk8
branches:
  only:
    - master
addons:
  apt:
    packages:
      - gnuplot
      - gnuplot-x11
      - python-pycodestyle
before_install:
  - cd ${TRAVIS_BUILD_DIR}/jepsen
script: |
  set -euo pipefail
  pycodestyle yugabyte/run-jepsen.py
  lein do clean, test

notifications:
  email:
    on_success: never
    on_failure: never
