name: Clojure CI

on:
  push:
    branches: [ "master-yb" ]
  pull_request:
    branches: [ "master-yb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cd yugabyte && lein run test
      id: run_lein_test
      continue-on-error: true
    - uses: nick-fields/assert-action@v1
      with:
        contains: "workload Must be one of"
        actual: ${{ steps.run_lein_test.outputs.value }}
