name: Clojure CI

on:
  push:
    branches: [ "master-yb" ]
  pull_request:
    branches: [ "master-yb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: echo "run_lein_test_output=$(cd yugabyte && lein run test)" >> $GITHUB_ENV
      continue-on-error: true
    - uses: nick-fields/assert-action@v1
      with:
        expected: "workload Must be one of"
        actual: ${{ env.run_lein_test_output }}
        comparison: contains
        
