name: Clojure CI

on:
  push:
    branches: [ "master-yb" ]
  pull_request:
    branches: [ "master-yb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      #run: echo "result=$(lein run test 2>&1 | grep Syntax)" >> $GITHUB_ENV
      run: echo "::set-output name=result::$(cd yugabyte && lein run test 2>&1)"
      id: lein_run_test_output
      continue-on-error: true
    - uses: nick-fields/assert-action@v1
      with:
        expected: "Syntax error reading source at"
        # actual: ${{ env.result }}
        actual: ${{ steps.lein_run_test_output.outputs.result }}
        comparison: notcontains
        
