name: Clojure CI

on:
  push:
    branches: [ "master-yb" ]
  pull_request:
    branches: [ "master-yb" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: echo "::set-output name=result::$(cd yugabyte && lein run test 2>&1 | grep 'Must be one of')"
      id: lein_run_test_output
    - uses: nick-fields/assert-action@v1
      with:
        # we do expect to see workload arg missing error here
        expected: "workload Must be one of"
        actual: ${{ steps.lein_run_test_output.outputs.result }}
        comparison: contains
        
